# Generated by Django 4.0.3 on 2022-03-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_user_interest_user_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_pw",
            field=models.TextField(default=False),
        ),
    ]
