# Generated by Django 4.0.3 on 2022-03-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_user_pw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_pw",
        ),
    ]
