# Generated by Django 4.0.3 on 2022-04-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
