# Generated by Django 4.0.3 on 2022-05-13 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='field_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewee_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_id',
            field=models.IntegerField(blank=True),
        ),
    ]
