# Generated by Django 4.0.3 on 2022-05-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interview_time',
            new_name='interview_date',
        ),
    ]
